### ISSUE TITLE
Multi job detection (conf file)

### ISSUE THREAD

**Issue by l2isbad** [l2isbad/go.d.plugin#3]
Config can be:

- `single job`
- `multi job`

Current detection approach (in python terms):
**if config has multi dimensional dicts then config is `multi job` else `single job`.**
Number of jobs == number of multi dimensional dicts.

Example:

```yaml
update_every: 1

key1:
  key2: value

key3:
  key4: value
```
 
As you understand it will be treated as `multi job`, but it may be not!

So if you want to create a one job with multi dimensional dict as options you forced to do it via `multi job` approach. I don't like it cause it adds `local` (or any other)  thing to the job name.

Should we leave this as is? i don't like it..

@ktsaou @Ferroin

**Comment by Ferroin** [comment]
I'm not particularly fond of it myself.  It seems more natural to me for the detection logic to check if there is more than one multi-dimensional dictionary, and treat it as multiple jobs only in that case.

**Comment by l2isbad** [comment]
If only the job config started with `job_`, it would solve all the problems.
I don't see any way to fix it without breaking old stuff :cry:

**Comment by ktsaou** [comment]
How does python solve it?

**Comment by ktsaou** [comment]
I still don't get the dilemma here. `key1` and `key3` are top level "unknown" keys (they don't match a keyword). So they are jobs. Each job is an object having a few members. `update_every` is both a top level keyword (default for all jobs) and a job attribute / member.

Could you please explain the problem a bit more?

**Comment by l2isbad** [comment]
Job option can be a multi dimension dict too. (like `web_log categories`). And we can't determine if this a global job option or a new job.

example:

```yaml

update_every: 1

categories:
  cat1: value1
  cat2: value2
```

To make it work properly I have to rewrite it to (which adds `job1` in the dashboard):

```yaml

update_every: 1

job1:
  categories:
    cat1: value1
    cat2: value2
```

**Comment by ktsaou** [comment]
Sorry, still can't get it.
Can you give a real-life example?

**Comment by l2isbad** [comment]
[Sensors plugin](https://github.com/firehol/netdata/blob/master/conf.d/python.d/sensors.conf)
config:

```yaml
#updatte_every: 1

types:
  - temperature
  - fan
  - voltage
  - current
  - power
  - energy
  - humidity

chips:
  - i8k
  - coretemp
```

It's valid. But what if `types` or `chips` would not be lists, but dictionaries?

**Comment by ktsaou** [comment]
So, this is a hypothetical question. In that case, once it is needed, you can use:

```yaml
job1:
  categories:
    cat1: value1
    cat2: value2
```

I thought the problem was about breaking existing functionality.
